# Generated by Django 3.2.5 on 2021-07-16 17:36

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='jobs/default.jpg', upload_to=post.models.image_upload),
        ),
    ]
