# Generated by Django 3.2.5 on 2021-07-16 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0006_auto_20210716_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_poster', to='auth.user'),
            preserve_default=False,
        ),
    ]
