# Generated by Django 3.2.5 on 2021-07-21 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0011_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(help_text='category', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='post.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, help_text='description', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='jobs/default.jpg', help_text='image', null=True, upload_to=post.models.image_upload),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=models.CharField(blank=True, help_text='phone_number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(help_text='poster', on_delete=django.db.models.deletion.CASCADE, related_name='job_poster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='post title', max_length=100),
        ),
    ]
