# Generated by Django 3.2.5 on 2021-07-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20210722_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
