# Generated by Django 3.2.5 on 2021-07-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_post_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured',
        ),
        migrations.AddField(
            model_name='post',
            name='hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(),
        ),
    ]
