# Generated by Django 3.2.5 on 2021-07-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20210726_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hot',
            field=models.BooleanField(default=False),
        ),
    ]
