# Generated by Django 3.2.5 on 2022-01-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_alter_post_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
