# Generated by Django 3.2.5 on 2021-07-26 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210726_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='max',
            new_name='maxd',
        ),
    ]
