# Generated by Django 3.1.5 on 2021-07-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210726_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dated',
        ),
        migrations.AlterField(
            model_name='profile',
            name='expiredate',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
