# Generated by Django 3.1.5 on 2021-07-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210726_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiredate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
